name: Check for Escaped Unicode Characters

on:
  push:
    paths:
      - 'fhir-ig-list.json'
  pull_request:
    paths:
      - 'fhir-ig-list.json'

jobs:
  check-unicode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for escaped Unicode characters
        run: |
          if grep -q '\\u' fhir-ig-list.json; then
            echo "Error: Escaped Unicode characters found in fhir-ig-list.json"
            echo "Failing lines:"
            grep -n '\\u' fhir-ig-list.json
            exit 1
          else
            echo "No escaped Unicode characters found."
          fi
